language: python
python:
  - "3.6.4"

# install dependencies
install:
  - pip install -r requirements.txt
  - pip install coverage

# command to run tests
script: 
  - python manage.py cov_test
  - python manage.py cover

after_success:
  - coveralls
